config/routes.rb
Rails.application.routes.draw do
root 'posts#index', as: 'home'

get 'about' => 'pages#about', as: 'about'

resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
validates :title, presence: true, length: {minimum: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def about
		@creators = 'Роботу виконали Олексієнко Владислав та Капелюший Сергій'	
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	def index
		@post = Post.all
	end

	def new
		@post = Post.new
	end
	def show
		@post = Post.find(params[:id])
	end
	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])

		if(@post.update(post_params))
			redirect_to @post
		else
			render 'edit'	
		end
	end
	def create
		#render plain: params[:post].inspect
		@post = Post.new(post_params)

		if(@post.save)
			redirect_to @post
		else
			render 'new'	
		end
	end

	private def post_params
		params.require(:post).permit(:title, :body)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
      <div>
        <h4 class="font-weight-bold mb-0">
          <%= image_pack_tag 'twitter-logo.png', size: '35x30', alt: 'Logo', :class => "mb-2"  %>
          <%= link_to "Twitter Blog", home_path, :class => "blog-title" %>
        </h4>
      </div>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse d-flex justify-content-end" id="navbarNavDropdown">
        <ul class="navbar-nav">
          <li class="nav-item active">
            <span class="nav-link font-weight-bolder"> <%= link_to "Головна сторінка", home_path, :class => "nav-link" %> <span class="sr-only">(current)</span></span>
          </li>
          <li class="nav-item">
            <span class="nav-link font-weight-bolder" href="#"><%= link_to "Про нас", about_path, :class => "nav-link" %></span>
          </li>
          <li class="nav-item">
            <span class="nav-link font-weight-bolder" href="#"><%= link_to "Додати пост", new_post_path, :class => "nav-link" %></span>
          </li>
        </ul>
      </div>
  </nav>

  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/pages/about.html.erb
<div class="container">
    <h4 class="justify-content-center text-center mt-2 display-4"><%= @creators %></h4>
</div>

app/views/posts/edit.html.erb
<h2 class="mt-2 display-4 text-center">Редагування поста</h2>
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
<% if @post.errors.any? %>
	<% @post.errors.full_messages.each do |msg| %>
		<div class="alert alert-danger"><%= msg %></div>
		<% end %>
	<% end %>
	
	 	<p>
	 		Назва
	 		<%= f.text_field(:title, {:class => 'form-control'}) %>
	 	</p>
	 	<p>
	 		Текст поста
	 		<%= f.text_area(:body, {:class => 'form-control'}) %>
	 	</p>
	 	<p class="text-center">
	 		<%= f.submit({:class => 'btn btn-success'})  %>
	 	</p>
	 	<% end %>

app/views/posts/index.html.erb
<h1 class='d-flex justify-content-center mt-2 display-3'>Головна</h1>	
<h4 class='mt-2 display-4'>Пости:</h4>	
<% @post.each do |post| %>
<div class="alert alert-light">
    <h3 class="font-weight-bolder"><%= post.title %></h3>
    <p><%= post.body %></p>
    <%= link_to "Читати далі", post_path(post), :class => 'btn btn-outline-primary' %>
</div>
<% end %>

app/views/posts/new.html.erb
<h2 class="mt-2 text-center display-4">Додати новий пост</h2>
<%= form_for :post, url: posts_path do |f| %>
<% if @post.errors.any? %>
	<% @post.errors.full_messages.each do |msg| %>
		<div class="alert alert-danger"><%= msg %></div>
		<% end %>
	<% end %>

<p>
	Назва
	<%= f.text_field(:title, {:class => 'form-control'}) %>
</p>
<p>
	Текст поста
	<%= f.text_area(:body, {:class => 'form-control'}) %>
</p>
<p class="text-center">
	<%= f.submit({:class => 'btn btn-success'})  %>
</p>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p><%= @post.body %></p>
<hr>
<p class="text-center"><%= link_to "Редагувати", edit_post_path(@post), :class => 'btn btn-warning' %></p>